---
# ldap_data_kania_ollenburg/tasks/basedn_and_ous.yml

- name: 'Create the baseDN'
  ldap_entry:
    dn: "{{ base_dn }}"
    objectClass:
      - 'domain'
      - 'dcObject'

- name: 'Create the users OU'
  ldap_entry:
    dn: "ou=users,{{ base_dn }}"
    objectClass:
      - 'top'
      - 'organizationalUnit'

- name: 'Create the groups OU'
  ldap_entry:
    dn: "ou=groups,{{ base_dn }}"
    objectClass:
      - 'top'
      - 'organizationalUnit'

- name: 'Create the Firma OU'
  ldap_entry:
    dn: "ou=Firma,{{ base_dn }}"
    objectClass:
      - 'top'
      - 'organizationalUnit'

- name: 'Create the Verwaltung OU'
  ldap_entry:
    dn: "ou=Verwaltung,ou=Firma,{{ base_dn }}"
    objectClass:
      - 'top'
      - 'organizationalUnit'

- name: 'Create the groups OU for Verwaltung'
  ldap_entry:
    dn: "ou=groups,ou=Verwaltung,ou=Firma,{{ base_dn }}"
    objectClass:
      - 'top'
      - 'organizationalUnit'

- name: 'Create the users OU for Verwaltung'
  ldap_entry:
    dn: "ou=users,ou=Verwaltung,ou=Firma,{{ base_dn }}"
    objectClass:
      - 'top'
      - 'organizationalUnit'

- name: 'Create the Produktion OU'
  ldap_entry:
    dn: "ou=Produktion,ou=Firma,{{ base_dn }}"
    objectClass:
      - 'top'
      - 'organizationalUnit'

- name: 'Create the users OU for Produktion'
  ldap_entry:
    dn: "ou=users,ou=Produktion,ou=Firma,{{ base_dn }}"
    objectClass:
      - 'top'
      - 'organizationalUnit'

- name: 'Create the groups OU for Produktion'
  ldap_entry:
    dn: "ou=groups,ou=Produktion,ou=Firma,{{ base_dn }}"
    objectClass:
      - 'top'
      - 'organizationalUnit'
