---
# ldap_data_kania_ollenburg/tasks/basedn_and_ous.yml

- name: 'Create the baseDN'
  ldap_entry:
    dn: "{{ base_dn }}"
    objectClass:
      - 'domain'
      - 'dcObject'
    bind_dn: "{{ rootdn_name }},{{ base_dn }}"
    bind_pw: "{{ rootdn_password }}"

- name: 'Create the users OU'
  ldap_entry:
    dn: "ou=users,{{ base_dn }}"
    objectClass:
      - 'top'
      - 'organizationalUnit'
    bind_dn: "{{ rootdn_name }},{{ base_dn }}"
    bind_pw: "{{ rootdn_password }}"

- name: 'Create the groups OU'
  ldap_entry:
    dn: "ou=groups,{{ base_dn }}"
    objectClass:
      - 'top'
      - 'organizationalUnit'
    bind_dn: "{{ rootdn_name }},{{ base_dn }}"
    bind_pw: "{{ rootdn_password }}"
