---
# ldap_data_kania_ollenburg/tasks/chapter_7_1_ous.yml

- name: 'Create the Firma OU'
  ldap_entry:
    dn: "ou=Firma,{{ base_dn }}"
    objectClass:
      - 'top'
      - 'organizationalUnit'
    bind_dn: "{{ rootdn_name }},{{ base_dn }}"
    bind_pw: "{{ rootdn_password }}"

- name: 'Create the Verwaltung OU'
  ldap_entry:
    dn: "ou=Verwaltung,ou=Firma,{{ base_dn }}"
    objectClass:
      - 'top'
      - 'organizationalUnit'
    bind_dn: "{{ rootdn_name }},{{ base_dn }}"
    bind_pw: "{{ rootdn_password }}"

- name: 'Create the groups OU for Verwaltung'
  ldap_entry:
    dn: "ou=groups,ou=Verwaltung,ou=Firma,{{ base_dn }}"
    objectClass:
      - 'top'
      - 'organizationalUnit'
    bind_dn: "{{ rootdn_name }},{{ base_dn }}"
    bind_pw: "{{ rootdn_password }}"

- name: 'Create the users OU for Verwaltung'
  ldap_entry:
    dn: "ou=users,ou=Verwaltung,ou=Firma,{{ base_dn }}"
    objectClass:
      - 'top'
      - 'organizationalUnit'
    bind_dn: "{{ rootdn_name }},{{ base_dn }}"
    bind_pw: "{{ rootdn_password }}"

- name: 'Create the Produktion OU'
  ldap_entry:
    dn: "ou=Produktion,ou=Firma,{{ base_dn }}"
    objectClass:
      - 'top'
      - 'organizationalUnit'
    bind_dn: "{{ rootdn_name }},{{ base_dn }}"
    bind_pw: "{{ rootdn_password }}"

- name: 'Create the users OU for Produktion'
  ldap_entry:
    dn: "ou=users,ou=Produktion,ou=Firma,{{ base_dn }}"
    objectClass:
      - 'top'
      - 'organizationalUnit'
    bind_dn: "{{ rootdn_name }},{{ base_dn }}"
    bind_pw: "{{ rootdn_password }}"

- name: 'Create the groups OU for Produktion'
  ldap_entry:
    dn: "ou=groups,ou=Produktion,ou=Firma,{{ base_dn }}"
    objectClass:
      - 'top'
      - 'organizationalUnit'
    bind_dn: "{{ rootdn_name }},{{ base_dn }}"
    bind_pw: "{{ rootdn_password }}"
