---
# ldap_data_kania_ollenburg/tasks/delete_everything.yml

- name: 'Delete regular users and sssd-user'
  ldap_entry:
    dn: "{{ item }}"
    state: 'absent'
  loop:
    - "cn=Stefan Kania,ou=users,{{ base_dn }}"
    - "cn=Andreas Ollenburg,ou=users,{{ base_dn }}"
    - "uid=sssd-user,ou=users,{{ base_dn }}"
    - "uid=ldap-admin,ou=users,{{ base_dn }}"
    - "cn=u1 Prod,ou=users,ou=Produktion,ou=Firma,{{ base_dn }}"
    - "cn=u1 Verw,ou=users,ou=Verwaltung,ou=Firma,{{ base_dn }}"
    - "cn=Al Verw,ou=users,ou=Verwaltung,ou=Firma,{{ base_dn }}"
    - "cn=Al Prod,ou=users,ou=Produktion,ou=Firma,{{ base_dn }}"

- name: 'Delete posix_group benutzer'
  ldap_entry:
    dn: "cn=benutzer,ou=groups,{{ base_dn }}"
    state: 'absent'

- name: 'Delete posix_group Produktion'
  ldap_entry:
    dn: "cn=Produktion,ou=groups,ou=Produktion,ou=Firma,{{ base_dn }}"
    state: 'absent'

- name: 'Delete posix_group Verwaltung'
  ldap_entry:
    dn: "cn=Verwaltung,ou=groups,ou=Verwaltung,ou=Firma,{{ base_dn }}"
    state: 'absent'

- name: 'Delete OUs'
  ldap_entry:
    dn: "{{ item }}"
    state: 'absent'
  loop:
    - "ou=users,{{ base_dn }}"
    - "ou=groups,{{ base_dn }}"
    - "cn=Verwaltung,ou=groups,ou=Verwaltung,ou=Firma,{{ base_dn }}"
    - "ou=users,ou=Verwaltung,ou=Firma,{{ base_dn }}"
    - "ou=groups,ou=Verwaltung,ou=Firma,{{ base_dn }}"
    - "ou=Verwaltung,ou=Firma,{{ base_dn }}"
    - "cn=Produktion,ou=groups,ou=Produktion,ou=Firma,{{ base_dn }}"
    - "ou=users,ou=Produktion,ou=Firma,{{ base_dn }}"
    - "ou=groups,ou=Produktion,ou=Firma,{{ base_dn }}"
    - "ou=Produktion,ou=Firma,{{ base_dn }}"
    - "ou=Firma,{{ base_dn }}"

# The base DN cannot be deleted...

- name: 'Delete ACLs'
  ldap_attr:
    dn: 'olcDatabase={2}mdb,cn=config'
    name: 'olcAccess'
    values: "{{ item }}"
    state: 'absent'
  loop:
    - '{5}to attrs=shadowLastChange by self write by * read'
    - '{4}to attrs=userPassword by self write by anonymous auth by * none'
    - '{3}to dn.children={{ base_dn }} by dn.exact=cn=ldap-admin,ou=users,{{ base_dn }} write by * break'
    - '{2}to dn.exact={{ base_dn }} by dn.exact=cn=ldap-admin,ou=users,{{ base_dn }} write by users read by * none'
    - '{1}to dn.exact=cn=subschema by * read'
    - '{0}to dn.exact="" by * read'

- name: 'Delete the debugging script'
  file:
    path: '/root/ldap_acl_debugging.sh'
    state: 'absent'

- name: 'Delete the directory containing the LDIF files'
  file:
    path: '/root/LDAP_configuration_via_ansible/'
    state: 'absent'
