---
# ldap_data_kania_ollenburg/tasks/main.yml

- name: 'Load variables'
  include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution | replace(' ', '_' ) }}{{ ansible_distribution_major_version }}.yml"
    - "vars_{{ ansible_distribution | replace(' ', '_' ) }}.yml"
    - "vars_{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
    - "vars_{{ ansible_os_family }}.yml"
  tags:
    - 'installation'
    - 'configuration'

- name: 'Run install_packages.yml'
  include_tasks: install_packages.yml

- name: 'Run basedn_and_OUs.yml'
  include_tasks: basedn_and_OUs.yml
  when:
    - 'not remove_everything | bool'

- name: 'Run chapter_3_5_group.yml'
  include_tasks: chapter_3_5_group.yml
  when:
    - 'not remove_everything | bool'
    - 'add_initial_testing_users | bool'

- name: 'Run chapter_3_5_users.yml'
  include_tasks: chapter_3_5_users.yml
  when:
    - 'not remove_everything | bool'
    - 'add_initial_testing_users | bool'

- name: 'Run sssd_user.yml'
  include_tasks: sssd_user.yml
  when:
    - 'not remove_everything | bool'

- name: 'Run chapter_7_1_ous.yml'
  include_tasks: chapter_7_1_ous.yml
  when:
    - 'not remove_everything | bool'
    - 'not add_initial_testing_users | bool'

- name: 'Run chapter_7_1_groups.yml'
  include_tasks: chapter_7_1_groups.yml
  when:
    - 'not remove_everything | bool'
    - 'not add_initial_testing_users | bool'

- name: 'Run delete_everything.yml'
  include_tasks: delete_everything.yml
  when:
    - 'remove_everything | bool'
